server:
  port: 8091

spring:
  application:
    name: customer

  cloud:
      function:
        definition : orderEventProcessor
      bindings:
        orderEventProcessor-in-0 :
          destination: order-created-event
        orderEventProcessor-out-0:
          destination: customer-verification-event

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - mappings