spring:
  application:
    name: order

  cloud:
      function:
        definition : orderCreatedSupplier;customerVerificationEventConsumer
      bindings:
        orderCreatedSupplier-out-0:
          destination: order-created-event
        customerVerificationEventConsumer-in-0:
          destination: customer-verification-event
